addSbtPlugin("com.github.sbt" % "sbt-ci-release"  % "1.5.12")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"    % "2.5.0")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"    % "0.11.0")
addSbtPlugin("org.typelevel"  % "sbt-tpolecat"    % "0.5.0")
addSbtPlugin("com.typesafe"   % "sbt-mima-plugin" % "1.1.3")
