addSbtPlugin("com.github.sbt" % "sbt-ci-release"  % "1.9.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"    % "2.5.2")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"    % "0.13.0")
addSbtPlugin("org.typelevel"  % "sbt-tpolecat"    % "0.5.2")
addSbtPlugin("com.typesafe"   % "sbt-mima-plugin" % "1.1.4")
