name: Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'
  push:
    tags-ignore:
      - "v*"
    branches:
      - "**"

jobs:

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        scala: [ 3.2.2 ]
        java: [ graalvm-ce-java17@22.3.0 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Compile and test
        run: sbt "+test; scalafmtCheckAll; scalafixAll --check; +mimaReportBinaryIssues"
