name: Test

on:
  workflow_dispatch:
  push:
    tags-ignore:
      - "v*"
    branches:
      - "**"

jobs:

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        scala: [ 3.3.1 ]
        java: [ graalvm-ce-java17@22.3.3 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compile and test
        run: sbt "+test; scalafmtCheckAll; scalafixAll --check; +mimaReportBinaryIssues"
